### ISSUE TITLE
HTTP 400 Bad request when muting

### ISSUE THREAD

**Issue by LemonArk** [denverquane/amongusdiscord#10]
Looks like the Bot is having issues muting tracked players in a tracked lobby. 

2020/09/15 19:28:51 HTTP 400 Bad Request, {"message": "Target user is not connected to voice.", "code": 40032}
2020/09/15 19:29:50 Issuing mute request to discord
2020/09/15 19:29:50 HTTP 400 Bad Request, {"message": "Target user is not connected to voice.", "code": 40032}
2020/09/15 19:29:50 Issuing mute request to discord
2020/09/15 19:29:50 HTTP 400 Bad Request, {"message": "Target user is not connected to voice.", "code": 40032}
2020/09/15 19:29:50 Issuing mute request to discord

**Comment by zombiestruck** [comment]
I'm getting this too.

**Comment by alzeric** [comment]
Also getting this issue, I've tried resetting the list, making sure it's tracking the proper channel.  Mainly notice it when doing a muteall

**Comment by denverquane** [comment]
New pre-release should address this issue
