### ISSUE TITLE
[Feature Request] "Sticky" game messages

### ISSUE THREAD

**Issue by buthed010203** [denverquane/amongusdiscord#100]
Add an option for game messages to "stick" to the bottom of a channel by basically just running `.au r` every time a message is sent in the channel.

**Comment by denverquane** [comment]
Appreciate the suggestion, but I don't think this is feasible, unfortunately. We already max out the discord api rate limits with all the mutes/unmutes, and from what I've seen, refreshing the status message is a 14 full api requests (1 for message, 13 emojis). Any users that post a message (forcing the status to refresh automatically) would incur 14 requests amidst the ~10 we already struggle to issue at round transitions

**Comment by buthed010203** [comment]
Yeah thats what I figured, the only way to do this would be to send the message and not add reactions automatically which is just less intuitive than #101
