### ISSUE TITLE
[Docker] Cannot provide json config file to container

### ISSUE THREAD

**Issue by bennydiamond** [denverquane/amongusdiscord#103]
Please allow for json config file usage in docked container.

Volume mapping to a config folder in which we could place our own config files to be accessed by app running in container.

**Comment by denverquane** [comment]
I haven't explicitly tried this, but I'm not sure what you mean? If you were to volume-mount the current directory into the docker container, then it would either 1. read the guild config from the current directory and use it, or 2. if the config fails to exist, it would create it. 

But in either cases, you could volume-mount the current dir, and the file would be referred/created either way.

**Comment by lukasschachner** [comment]
> I haven't explicitly tried this, but I'm not sure what you mean? If you were to volume-mount the current directory into the docker container, then it would either 1. read the guild config from the current directory and use it, or 2. if the config fails to exist, it would create it.
> 
> But in either cases, you could volume-mount the current dir, and the file would be referred/created either way.

Yeah and it works i have written a `docker-compose.yml` which has these volumes setup could provide it if you want
should also just work with the `-v`  tag in the normal `docker run` command
