### ISSUE TITLE
v2.2.4 Unlinks players at end of game occasionally

### ISSUE THREAD

**Issue by gjones12687** [denverquane/amongusdiscord#106]
v2.2.4-prelease sometimes unlinks all players at the end of the game other than the person running capture. Seems to happen most often with those on mobile. 
I expect it depends on whether the person running capture clicks play again before everyone else, and the system now sees no-one in lobby so unlinks everyone.

I suggest either save state as end game and only unlink after a time has passed, or only unlink if they leave game and discord - I may make a pull request for this if time permits

**Comment by MetricMike** [comment]
Hey, gjones, can you verify this is still occurring with the 2.2.4 released a few hours ago? This got caught pretty quickly in the discord chat, but Soup opted to re-release rather than increment the version number.

**Comment by gjones12687** [comment]
@MetricMike Do you know what time re-release was, I built from source at about 10pm GMT from the v2.2.4-prerelease tag commit 57a780c9462be8aa7941646567d513ec0ec6cd8d 
Will test against master tonight and get back to you.

**Comment by MetricMike** [comment]
Around 9pm gmt, so possible

**Comment by gjones12687** [comment]
Confirming this was fixed with a8602f closing
