### ISSUE TITLE
[Feature Request] Automatically link players based on nick

### ISSUE THREAD

**Issue by buthed010203** [denverquane/amongusdiscord#113]
If someones discord nick is the same as a player in the game and said discord user is in the tracked vc, automatically link them. This would work really well when paired with the set nickname function of the bot.

**Comment by denverquane** [comment]
Just came up with a working prototype on a branch, should be in the next release along with a bunch of other fun stuff :)

**Comment by buthed010203** [comment]
Fixed in [2.3.0](https://github.com/denverquane/amongusdiscord/releases/tag/v2.3.0)
