### ISSUE TITLE
Any way to use <GUILD_ID>.config.json while using HerokuApp ?

### ISSUE THREAD

**Issue by se7enek** [denverquane/amongusdiscord#115]
Simple as that, since theres no way of saving configs using Heroku, maybe there is other way of accessing config?

//i thought i get it but apparently i dont.

**Comment by denverquane** [comment]
Yeah the new `.au settings` command that was merged into master should do the trick. The settings aren't saved to the json file in the current master branch, but our next release will support this as well.
