### ISSUE TITLE
Problem with changing the lobby

### ISSUE THREAD

**Issue by LikeADidi** [denverquane/amongusdiscord#123]
I try to tell my problem, but my englisch is not very well.
I started the bot correctly and linked the bot with discord.
When i change the lobby in Among us, the bot change also the Room Code, but does not recognize that i am in the lobby.
The "Players Linked" stays on "0/0". And when another user join the Lobby, the bot tracks the other user, but not me.
I tried to link me manually, but it does not work. The console says "I couldn't find any player data for that color; is your capture linked?"

![First Lobby](https://user-images.githubusercontent.com/72576687/95505328-76619c00-09ae-11eb-8bf7-c986828fa6b4.png)

![Secong Lobby](https://user-images.githubusercontent.com/72576687/95505355-80839a80-09ae-11eb-8b31-a907a2990c1b.png)

![Second Lobby](https://user-images.githubusercontent.com/72576687/95505380-89746c00-09ae-11eb-9f4c-4cd3671e6673.png)

**Comment by LikeADidi** [comment]
#Edit: When i change my color in Among us, the bot tracks me.

**Comment by buthed010203** [comment]
Yeah its a bit wonky but it works most of the time, a simple `.au r` might fix it.

**Comment by dawnofwar911** [comment]
It doesn't seem to, it's if you change lobby it won't confirm the host is still in the lobby if you're hosting the game, at least that's the probelm with me as i host them. Any refresh doesn't help but the work around i've found is if you change your colour the capture will then recognise you as being in the room and you can react correctly and link yourself.

**Comment by buthed010203** [comment]
Yeah the issue seems to be joining a lobby with the capture linked, I guess any sort of moving between games with the capture linked is broken as well. The solution would be to just relink whenever you move lobbies.

**Comment by dawnofwar911** [comment]
A manual link didn't work though as it's the capture that doesn't recognise you, it's as if it doesn't do a scan after the tranistion from menu to lobby

**Comment by buthed010203** [comment]
Ah turns out it was miscommunication between the bot and the capture, fixed in a testing build.

**Comment by denverquane** [comment]
This has been fixed in 2.3.1, but I appreciate you bringing it to our attention and providing details :)
