### ISSUE TITLE
Sometimes last 2-3 users are unmuted after 10+ seconds

### ISSUE THREAD

**Issue by se7enek** [denverquane/amongusdiscord#126]
So basically on full game, last 2 maybe 3 ppl are unmuted after long while. It's hard to wait on discussion phase till bot unmutes all cuz 10 seconds of being silent is lame. Anyway I assume it's related to bot api requests limit, yet would be nice if unmuting during discussion would be priority over ie. changing the embed's title.

**Comment by denverquane** [comment]
Yes, this is related to the Discord API limits. For the record, the current code DOES prioritize unmuting players before updating the embed message. Discord, however, lets the embed edit go through immediately though, as the rate limits for player changes (like mutes/deafens) are a totally separate rate limit "bucket" than the embed edits.

I recommend you try the latest 2.3.1 release; you can provide a second Bot token (use the exact same setup as the initial bot, and make sure to invite the 2nd bot to your server), and this will be used to issue 1/2 the mute/deafen requests. Playing with a full lobby earlier, we had 0 delays on full 10 person mutes/unmutes, it was really really nice
