### ISSUE TITLE
Error linked, but colors not working

### ISSUE THREAD

**Issue by Palamedeus** [denverquane/amongusdiscord#130]
It keeps saying
 I couldn't find any player data for that color; is your capture linked?
Even though I have linked the capture, and it says that in the text channel (NAME is running an Among Us game!
The game is happening in any voice channel!).
Is there a way to fix this?

**Comment by abdellahaski** [comment]
Try to spam change your player color in-game to see if the capture pick it up, this happens from time to time AFAIK.

**Comment by Palamedeus** [comment]
Still not working

**Comment by abdellahaski** [comment]
are you in a game? what does your Current State says MENU or LOBBY? 
Are you using the cracked version of the game?

**Comment by kenajCZ** [comment]
> are you in a game? what does your Current State says MENU or LOBBY?
> Are you using the cracked version of the game?

It's any way to use bot on cracked version?

**Comment by denverquane** [comment]
> > are you in a game? what does your Current State says MENU or LOBBY?
> > Are you using the cracked version of the game?
> 
> It's any way to use bot on cracked version?

No.
