### ISSUE TITLE
No "final.txt"?

### ISSUE THREAD

**Issue by VANTA-BLACK** [denverquane/amongusdiscord#138]
The installation instructions say "Download the latest release executable (.exe) and final.txt" yet the newest release doesn't seem to have one. I (likely quite obviously) have little idea what I'm doing, so I'm checking before installing lest I stuff something important up.

![image](https://user-images.githubusercontent.com/32715714/95688200-0a07c680-0c54-11eb-85f8-3ff16907226c.png)

**Comment by denverquane** [comment]
https://github.com/denverquane/amongusdiscord#easiest just make a text file, I forgot to attach one for this release

**Comment by VANTA-BLACK** [comment]
Thank you!
