### ISSUE TITLE
Unable to link, websocket not associated with guilds

### ISSUE THREAD

**Issue by andermoran** [denverquane/amongusdiscord#150]
2020/10/14 14:43:30 2.3.2-Prerelease
2020/10/14 14:43:30 [Info] Invalid or no particular PORT (range [1024-65535]) provided. Defaulting to 8123
2020/10/14 14:43:30 [Info] No valid SERVER_URL provided. Defaulting to http://localhost
2020/10/14 14:43:30 [Info] No EXT_PORT provided. Defaulting to PORT
2020/10/14 14:43:30 Using ./ as the base path for config
2020/10/14 14:43:30 Success in initializing the local Filesystem as the Storage Driver
2020/10/14 14:43:30 Bot is now running.  Press CTRL-C to exit.
2020/10/14 14:43:34 Serving at localhost:8123...
2020/10/14 14:43:34 Successfully loaded config from storagedriver for 765965708080840714
2020/10/14 14:43:34 Added to new Guild, id 765965708080840714, name Squad's Among Us
2020/10/14 14:43:34 [This is not an error] No explicit guildID provided for emojis; using the current guild default
2020/10/14 14:45:07 connected: 1
2020/10/14 14:45:08 Received connection code: "A270E7B3"
2020/10/14 14:45:08 No guild has the current connect code of A270E7B3
2020/10/14 14:45:08 phase received from capture:  3
2020/10/14 14:45:08 This websocket is not associated with any guilds
2020/10/14 14:45:45 phase received from capture:  0
2020/10/14 14:45:45 This websocket is not associated with any guilds
2020/10/14 14:45:45 player received from capture:  {"Action":0,"Name":"Ander","IsDead":false,"Disconnected":false,"Color":0}
2020/10/14 14:45:45 This websocket is not associated with any guilds
2020/10/14 14:45:45 lobby: {"LobbyCode":"EYBMRQ","Region":0}
2020/10/14 14:45:45 I don't have a record of any games with a lobby or connect code of EYBMRQ

**Comment by Snow4DV** [comment]
Having the same problem. 2.3.1 worked ok

**Comment by Snow4DV** [comment]
![Screenshot_11](https://user-images.githubusercontent.com/32912696/96259771-bf28de80-0fc6-11eb-8966-a09b0f2854bd.png)
Here is what i have in capture/discord/bot

**Comment by Snow4DV** [comment]
If i use PORT = and EXT_PORT = settings nothing happens after linking to capture. If i use default 8123 port it seems to be working but everytime capture connects it disconnects instantly and connects back. I even got such bug with it: 
![scr](https://user-images.githubusercontent.com/32912696/96260605-ed5aee00-0fc7-11eb-8128-b6367cd7b4af.png)

**Comment by Snow4DV** [comment]
Fixed this! Just updated the capture app to the latest version (previous one was loaded 20h ago and i couldn't realize that there was a newer one uploaded 9h ago)
