### ISSUE TITLE
Linking capture error with bot on Heroku

### ISSUE THREAD

**Issue by 7xavierl** [denverquane/amongusdiscord#159]
I've tested the bot running on my PC and it worked perfectly. Then, i tried to upload it to Heroku, following the READ.ME instructions. The bot appers online on my Discord server, accepts the command ".au new" and send me the url to start capture.
When the capture app runs, i get this error: 
[ClientSocket]: Attempting to connect to host https://your-app.herokuapp.com:443 with connect code 79C57D07
[ClientSocket]: One or more errors occurred. (The server returned status code '502' when status code '101' was expected.)

![image](https://user-images.githubusercontent.com/55811443/96324512-8c97d980-0ff8-11eb-9c9c-8f2e2092ee69.png)

![image](https://user-images.githubusercontent.com/55811443/96324538-a802e480-0ff8-11eb-8467-ac56cc7f9975.png)

**Comment by INGY23** [comment]
You need to update SERVER_URL to your app URL

**Comment by 7xavierl** [comment]
> You need to update SERVER_URL to your app URL

Worked perfectly!
What a rookie mistake :(

Thanks for the help!!!
