### ISSUE TITLE
Probleme with providing room code 

### ISSUE THREAD

**Issue by XSeRGiO4** [denverquane/amongusdiscord#161]
![Capture](https://user-images.githubusercontent.com/73010762/96328770-44030f00-103e-11eb-9144-ddbbc73f8454.PNG)
 
this is a probleme im facing ... 
thnx in advance

**Comment by abdellahaski** [comment]
if you already in a game (since it isn't detecting you) try spam changing your in-game color until it does detect your game

**Comment by XSeRGiO4** [comment]
Sorry bro but it didnt work ... Ps: im running a cracked version of the game and did not buy it from steam .. so any other solution ?

**Comment by denverquane** [comment]
We do not support cracked, read the readme
