### ISSUE TITLE
[Feature Request] At meeting time, auto move dead players to a Ghosts channel until game is over, then move them back

### ISSUE THREAD

**Issue by lutzke** [denverquane/amongusdiscord#162]
Hi,

In some of the games I've been in, I noticed that the dead players like chatting about what's going on in the in-game text chat. Since these players can no longer affect the outcome of the game, I thought a nice feature would be to move dead players to a ghosts channel (but only at meeting time, when everyone actually knows they are dead) so that dead players aren't just sitting there in silence until the game is over. Once the game ends, the dead players should be automatically moved back to the primary voice channel.

This could be an optional feature users could specify with a command, much like the current `.au link`

I love the idea of this Discord bot and hope to test it out this weekend with some friends. Thanks for making your work on this public for everyone to use.

**Comment by denverquane** [comment]
Please use the bot before requesting new features... 

Dead players can already chat during rounds with our bot :) we've considered the moving players functionality, but it adds a lot of complexity for not much advantage when dead players can already talk with the current functionality set

**Comment by lutzke** [comment]
Ahh sorry, I didn't realize this was already a feature!
