### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by pmalek** [denverquane/amongusdiscord#164]
Any chance of making this work on Linux? In terms of go source I'm willing to help.

The only part I couldn't make working was the capture. It's written in .NET and even though I have wine installed and I am able to run the capture links and the capture shows up the view is a bit scrambled (showing up the association code though) and it doesn't seem to connect properly (bot's status message on discord server channel doesn't update).

This is the message:

```
Main Menu

@ppp is running an Among Us game!
The game is happening in the General voice channel!
```

**Comment by ajc133** [comment]
A similar issue was already closed. This person linked their fork https://github.com/denverquane/amongusdiscord/issues/104#issuecomment-708699759

**Comment by pmalek** [comment]
Nice. Ok, that's a good starting point for me, thanks!
