### ISSUE TITLE
Faster win detection

### ISSUE THREAD

**Issue by ZimGil** [denverquane/amongusdiscord#17]
I assume that it is possible to detect a crewmates win by detecting the "Confirm Ejects" text.

When it says "0 Impostors Remains", it can be considered as a crewmates win - game over. 

At this point the bot should already think meeting is over (cause we had the results) and try to mute all. This case should stop to mutes and unmute all.

**Comment by denverquane** [comment]
We are ditching the screen capture for more reliable methods of detection, but yes, faster detection will be coming as part of the next major release :)
