### ISSUE TITLE
Bot wont unmute during discussion

### ISSUE THREAD

**Issue by no7thing** [denverquane/amongusdiscord#2]
The bot can recognize the starting screen, but won't unmute people when emergency meetings are called or when the game ends.

**Comment by denverquane** [comment]
Hey thanks for filing the issue. 

I'm currently tracking this (some users are reporting problems in the discord as well: https://discord.gg/ZkqZSWF), but if anyone can provide some debug logs (screencaps or copy/paste) when the situation occurs, that would help me a lot. 

The console window where you run the bot should report some information as far as if it detects the game changing (which mean the screen capture is not the issue), or if the Mute/Unmute commands aren't being applied to all players, etc.

If you encounter an issue specifically with the capture (the bot doesn't detect the transitions between phases at all), I can provide some additional debug instructions to help tease out the problem.

**Comment by denverquane** [comment]
[Releases 1.3.3 and later](https://github.com/denverquane/amongusdiscord/releases) should hopefully resolve some of the issues (there was a race condition with some users where the game unmuted, and then immediately re-muted some players when a discussion began), but please anyone lmk if you still see this behavior past 1.3.3

**Comment by mopquill** [comment]
Still seeing this in 1.4.2 yesterday and today. I hadn't yet enabled debug logs, I've now enabled them. If I see a repeat, I will report back with them.
