### ISSUE TITLE
Bot repeat muting options

### ISSUE THREAD

**Issue by LightningGHub** [denverquane/amongusdiscord#23]
So it just came to mind that it would be great if you could add a command (that can be locked to a single role), that would be able to turn off the looping of the server mutes. Like you type in the command into discord and after that the bot only mutes people once and ignores it until further inputs. If the bot messes up once we just get stuck with no ability to speak currently.
For that part a force unmute would be great too. Not the current one but one that actually makes it stop muting people until a new input comes in (new round etc.)

**Comment by KMontag42** [comment]
this should be fixed with the newest release (2.0.5). going to close this ticket. if you get these issues again please open a new one! thanks!
