### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by moveit124** [denverquane/amongusdiscord#25]
I just wanted to throw this out there as an option for making the bot more autonomous and not needing to be run on a players computer.  The problem with this is having to share a bot token with other users who might use that maliciously.  Which limits the amount of people in a server being able to use the bot.

Idea 1
Instead of having the player run it on there PC just have them live stream instead.  Have the bot search a specific voice channel for players live.  When it finds a player live (or maybe make it a command to like .au startgame or something) it looks at there live stream to watch the among us game and uses that data to auto-mute/unmute.  

Idea 2
Make a client side bot and server side bot.  Server side bot is always running.  Player runs client side bot and it connects to server side of the bot that is running on the discord servers and it transfers that data of the screen captured to the bot running on the server side which does all the actions.

I am not a dev and honestly have no idea if these things are super difficult to do or not.  I just thought I would make the suggestion from a user who likes the idea of the bot but has a problem where its only used when I am online because I dont want to give out a bot token to random people in my community.

**Comment by denverquane** [comment]
Thanks for your suggestion; your idea 2 is already implemented in developer builds, and will be included in the next major release! 👍 Stay tuned!
