### ISSUE TITLE
Hosting bot online

### ISSUE THREAD

**Issue by abhiman2387** [denverquane/amongusdiscord#27]
Hey. This is brilliant bot. Thanks for the same. I was just going through some stuff and found that heroku lets you host a discord bot for free. Are you aware of the same? Maybe you can try it out? Sorry if this seems silly.

Thanks and Regards,

**Comment by Martijnpold** [comment]
Since the bot uses a screen scraper I doubt that that's possible. The bot needs access to your screen and Heroku doesn't provide that sort of functionality as far as I'm aware. So you pretty much have to host it on a machine of a player that is present in the game.

**Comment by denverquane** [comment]
We have split the bot into two portions already for our side dev development (on the decouple branch). We will likely always need to run the capture locally, but the discord portion is totally decoupled from the capture now (hence the name of the branch) :)
