### ISSUE TITLE
[Suggestion] Music Bot support

### ISSUE THREAD

**Issue by zjamnik** [denverquane/amongusdiscord#28]
I'd be nice to have a support for a dedicated music user. It would be a reverse of other users mute status. Unmuted during the game and muted at discussion time.

**Comment by denverquane** [comment]
Great idea! Our latest development efforts on the decouple branch (hoping to merge into master soon) will prevent from muting non-participating players (or music bots) when rounds begin, but we haven't quite yet worked on a functionality to reverse the mute for specific bots/users. One problem we might encounter is the speed at which mutes/unmutes happen; we saw issues with the speed of mute/unmute for 10 total users on the current master branch, so we want to make sure it doesn't result in delays for the other players :)

**Comment by KMontag42** [comment]
this should work now as long as the music bot isn't tracked by the discord bot.

closing.
