### ISSUE TITLE
Waiting for Game to begin...

### ISSUE THREAD

**Issue by officialnochill** [denverquane/amongusdiscord#3]
All other steps working correctly and the game is in fullscreen. 
But it is still stuck on that message.

**Comment by Kordonme** [comment]
Same here

**Comment by vinanrra** [comment]
Same here with spanish language, gonna test with English

**Comment by vinanrra** [comment]
Works with English without problem

**Comment by denverquane** [comment]
New pre-release should address this issue too :)
