### ISSUE TITLE
Instead of muting can we move the dead to a different channel?

### ISSUE THREAD

**Issue by ra-jain** [denverquane/amongusdiscord#32]

**Comment by Aasikki** [comment]
This is a good idea! Would make spectating more fun.

**Comment by vinanrra** [comment]
+1

**Comment by karmette** [comment]
the issue is that people will hear the sound of someone getting moved, and would know when someone dies. plus if someone has discord overlay on they will know who died.

**Comment by denverquane** [comment]
> the issue is that people will hear the sound of someone getting moved, and would know when someone dies. plus if someone has discord overlay on they will know who died.

We already have a method to stagger the dead player emojis until the discussion phase. We would wait to move players until the discussion phase

**Comment by rorosaurus** [comment]
I was thinking about this today and I think a system with a channel for dead voice chat would be awesome. But that dead voice channel would miss out on any discussion from the alive players. I think an ideal setup would look like this:

Once, at the beginning of every task phase, all dead players are moved to a separate dead voice chat channel and unmuted, so they can rage/discuss with other dead people. Everyone remaining in alive voice chat is force muted.

Once, at the beginning of every discussion phase, all dead players are muted and moved back to alive voice chat. Alive players are force unmuted.

This allows dead players to hear the discussion and remain clued in to how crewmates are feeling/voting. Dead can no longer voice chat with other dead during discussion (but they can type via the ingame chat!)

This setup allows dead players to chat casually and not get bored once they complete their tasks. It would certainly be more fun to be screaming at clueless crewmates together!

**Comment by denverquane** [comment]
Hey thanks; the latest 2.0.2 pre-release actually already has this behavior. It mutes+deafens alive players during the round (so they can't hear dead players), but the dead players can speak openly. Then at discussion, alive players are unmuted/undeafened, but dead players are muted. This should address the suggestions posted above; I don't think we'll look at moving functionality for the near future (it would blow past the Discord API rate limits even moreso than the current implementations).
