### ISSUE TITLE
Reset command

### ISSUE THREAD

**Issue by AlexAegis** [denverquane/amongusdiscord#35]
It's working nice, I like it!

Would be nice to have an .au reset command that resets everything (Especially the mutes) because if I take down the processes mid game the voice channels stay muted until I restart everything and trigger some event like getting in a lobby, this way if the server crashed, I can restart it and reset.

Or better yet, the bot should make sure to reset everything on shutdown (unmuting channels) and on startup

**Comment by denverquane** [comment]
Yep, great idea. We need a formal way to "end" the .au game for sure, and the bot should probably try and unmute all users before exiting as well

**Comment by denverquane** [comment]
Just added a `.au end` to completely end the game (and unmute all players), but also added an `.au force <stage>` to help override if the capture portion doesn't report the right state :)
Ex: `.au f discuss`
