### ISSUE TITLE
Autotrack

### ISSUE THREAD

**Issue by AlexAegis** [denverquane/amongusdiscord#36]
Would be nice to automatically select a voice channel to autotrack if there is one with the same name as the text channel within (or maybe without? Some servers group these differently) the same group

![image](https://user-images.githubusercontent.com/16900547/93758353-918b8800-fc08-11ea-829d-c1bfc4c26760.png)

**Comment by denverquane** [comment]
In the future, we will probably have the bot auto-track whatever voice channel the user that called `.au new` is in

**Comment by denverquane** [comment]
This is done as of 2.0.5 :)
