### ISSUE TITLE
.au unmuteall/muteall and other commands not working in server

### ISSUE THREAD

**Issue by anshmishra** [denverquane/amongusdiscord#4]
The commands with the prefix .au are not working when typed in the server. I accidentally closed the game while playing and 10 players in my server were left server muted

**Comment by denverquane** [comment]
Hey, sorry that happened. I can't really help fully diagnose the issue without screenshots of your logs or console log output though. Sometimes the bot can struggle to issue all mute/unmute commands quickly; this is a limitation of Discord's API to prevent bots from flooding their servers. This means sometimes it can take 6+ seconds for all mute/unmute commands to be applied to all 10 players, and sometimes longer if Discord manually flags the bot and rate-limits it
