### ISSUE TITLE
Add security to connecting to a server

### ISSUE THREAD

**Issue by Gattag** [denverquane/amongusdiscord#45]
Add a command that will provide the user a key to be used when connecting the capture software to the discord bot. I currently submitted a pull request in the capture software to allow the user to change the host it can connect to, with this anyone can connect to the bot and control whatever game they like. If a key is provided for a new game instance and only using that key can the game instance be controlled, the security issue is avoided when connecting to the discord bot server is opened to any globally routable address

**Comment by denverquane** [comment]
Added in 2.0.4 :)
