### ISSUE TITLE
Nothing happens in the Discord channel after linking capture

### ISSUE THREAD

**Issue by ThaddeusKKR** [denverquane/amongusdiscord#49]
![image](https://user-images.githubusercontent.com/49682825/94004051-ab76c780-fdce-11ea-8ace-551128b4ecf4.png)
![image](https://user-images.githubusercontent.com/49682825/94004060-b03b7b80-fdce-11ea-8a4c-cde71a23c072.png)

**Comment by ThaddeusKKR** [comment]
The embed just stays at no capture linked

**Comment by Midrule** [comment]
You didn’t write “connect 80ACD0” you just said the password so it didn’t do anything. The bot even tells you to write “connect” in with it

**Comment by ThaddeusKKR** [comment]
I did. I tried it with and without (also relaunching the program) and it did not work both times.

**Comment by ThaddeusKKR** [comment]
Is the embed in Discord supposed to be edited after the linking?

**Comment by Midrule** [comment]
If you do .au n and paste the “connect 826CA2” or whatever into the capture while they’re both on. It should work. Do you have 2.04 and 2.03 of capture?

**Comment by ThaddeusKKR** [comment]
Must the two files be in the same folder?

**Comment by Midrule** [comment]
They don’t necessarily have to, but I highly recommend it, that could fix the problem for some people

**Comment by ThaddeusKKR** [comment]
Nevermind, I somehow got it to work by just trying a lot more times. It might just be inconsistent. I'll reopen or make a new issue if this happens again. Thanks for your help!
