### ISSUE TITLE
Amongusdiscord.exe crashing

### ISSUE THREAD

**Issue by stormlv368** [denverquane/amongusdiscord#50]
The amongusdiscord.exe part of the bot seems to crash. It crashes more frequently when muting/unmuting players at the beginning of the round, however has happened in the middle many times.

I tried about 8 times but was unsuccessful in completing a whole game without it crashing.

I trialed the bot several times with just myself and an alt account and it worked fine. however once playing with 8 people in the discord it crahes.

The final log messages before crashing was:
HTTP 404 Not Found, {"message": "Unknown Message", "code": 10008}

I was using version 2.0.3 but did encounter the same problem in the couple of times I tested 2.0.4

Thanks

**Comment by CloakingPotion** [comment]
Just a heads up, I ran into this error as well but not from running in it an 8 player game (I haven't done that quite yet). Instead, I've been working on a modified version for use in my server. I received this message by deleting this message before the last reaction was added:
![image](https://user-images.githubusercontent.com/4021155/94052192-d09b1400-fd95-11ea-9dae-33ac761a2039.png)

**Comment by stormlv368** [comment]
> Just a heads up, I ran into this error as well but not from running in it an 8 player game (I haven't done that quite yet). Instead, I've been working on a modified version for use in my server. I received this message by deleting this message before the last reaction was added:
> ![image](https://user-images.githubusercontent.com/4021155/94052192-d09b1400-fd95-11ea-9dae-33ac761a2039.png)
> 
> To help troubleshoot, perhaps there is something deleting the message before the reacts are able to be applied. @stormlv368, what bots do you currently have installed? And is it possible one of them are deleting messages from the AmongUsDiscord bot?
> 
> To assist further, I was able to find the section of the code that is applying the reactions:
> 
> https://github.com/denverquane/amongusdiscord/blob/4b972971baf087b45f2e76f9192a14e52af8413e/discord/message_handlers.go#L32-L45
> 
> https://github.com/denverquane/amongusdiscord/blob/4b972971baf087b45f2e76f9192a14e52af8413e/discord/message_handlers.go#L101-L106
> 
> I'm not entirely sure how the MessageReactionAdd method is handled, but it seems to be using HTTP methods to achieve it.
> 
> It's also possible these two issues are not related. And it's just two different HTTP errors.
> 
> *Additionally, although I did see this error message for each react that wasn't able to find the message, it didn't crash for me. It just kept going.

The message is not being deleted. And no other bots should be deleting the messages.

However the bots I have are as followed:
Dyno Bot - Majority of the functions are turned off though (especially auto mod which is the main thing that would try and interfere with the among us bot.)
Ephemeral Roles - Adds a role to every user that joins a voice channel (can not manage messages)
Reaction Roles - Only used in one channel so shouldn't be interfering with the bot.

One thing that may be the problem is the fact that users are reacting to the message as soon as their colour pops up, rather than waiting until all the colours are there. I am unsure if this is the problem, and I am yet to test it properly - I will be testing it tonight with a few friends.

Thanks.

**Comment by denverquane** [comment]
Just to check in:

I'm almost positive that this is a race condition of some sort. We're definitely not locking/unlocking the status message properly, and it is accessed by **many** asynchronous parts of the code. I went ahead and made a "threadsafeRefactor" branch; this was going to be necessary at some point, so it might as well be now, while the codebase is still growing but not out of control. 

So far I have all the in-game user data, and channels being tracked wrapped up in thread-safe accessors/transformer functions. Next step is for me to refactor the discord-related userData (the largest portion), and as we've seen here, **definitely** the singular status message, to both be locking/threadsafe.

Just wanted to post and let you guys know it's being actively worked 👍

**Comment by stormlv368** [comment]
Just an update.

I have done some extra testing and have found that if you let the bot react with all the colours before linking accounts then everything works perfectly. Other than a few minor hiccups, however not once did the bot crash for me.

Thanks

**Comment by KMontag42** [comment]
have you tried the latest release (2.0.5)? let us know if it works for you. thanks!
