### ISSUE TITLE
No reactions

### ISSUE THREAD

**Issue by ThatCreeper** [denverquane/amongusdiscord#52]
The bot doesn't add any reactions automatically.

I'm wondering if I have to do that manually, or if I'm doing something wrong.

**Comment by denverquane** [comment]
It can take a long time for the emojis to be added to your server; check your logs. The Discord API is painfully low in letting bots manage emojis

**Comment by ThatCreeper** [comment]
ok, thanks

**Comment by ThatCreeper** [comment]
All that I can see in the logs related to emojis are that it's not snowflake

**Comment by ThatCreeper** [comment]
Nevermind, it works now :)
