### ISSUE TITLE
Add a config file?

### ISSUE THREAD

**Issue by aflacc** [denverquane/amongusdiscord#55]
I think it would be nice to customize a few things via a config file. Some of these would be:
- prefix **[prefix]** _whatever prefix to call the bot commands you would prefer_
- permissions **[all/owner/admin]** _would be "all","owner" and "admin". would basically change who can actually use the bot._
- custom emojis **[true/false]** _a true/false setting that would if true, add the custom emojis. if false, use default emojis_
- defaults **[a,b]** _Would have multiple values. "a" is default region, "b" is default voice channel._ 
- mute **[instantly/discussion]** _Allows you to set when players are muted when dead. You can make them mute once discussion when everyone is aware they died, or have them mute on death, to prevent people giving it away._
- status **[text]** _Set the status of the bot._

**Comment by KMontag42** [comment]
>     * prefix **[prefix]** _whatever prefix to call the bot commands you would prefer_

this is planned: https://github.com/denverquane/amongusdiscord/issues/56

>     * permissions **[all/owner/admin]** _would be "all","owner" and "admin". would basically change who can actually use the bot._

not a bad idea, i'm assuming you are implying permission based on user role. will talk to other devs.

>     * custom emojis **[true/false]** _a true/false setting that would if true, add the custom emojis. if false, use default emojis_

not sure what you mean by this, there aren't enough "default" emojis to support selecting all 12 possible colors. likely will not do.

>     * defaults **[a,b]** _Would have multiple values. "a" is default region, "b" is default voice channel._

good idea, [added](https://github.com/denverquane/amongusdiscord/issues/66)

>     * mute **[instantly/discussion]** _Allows you to set when players are muted when dead. You can make them mute once discussion when everyone is aware they died, or have them mute on death, to prevent people giving it away._

not too sure what you mean by this, have you tried our newest release yet? people aren't able to give away anything.

>     * status **[text]** _Set the status of the bot._

not too sure what you mean by this.

**Comment by denverquane** [comment]
Most of these have been officially added as of now, and the others are no longer relevant or not being worked, closing
