### ISSUE TITLE
Better mute/deaf handling based on alive-ness

### ISSUE THREAD

**Issue by KMontag42** [denverquane/amongusdiscord#58]
Currently we just iterate through an un-sorted player list when doing mute/deaf handling.

https://github.com/denverquane/amongusdiscord/blob/master/discord/guild.go#L117

It would be in our best interest to sort this iterator based on in-game alive-ness (with alive players being first) to ensure that there is no potential for audio sneaking through rate limited requests.

**Comment by denverquane** [comment]
This is done and merged :)
