### ISSUE TITLE
Docker and capture issue?

### ISSUE THREAD

**Issue by jackbayliss** [denverquane/amongusdiscord#59]
I've got the docker server running fine via AWS. When doing .au new ABCD eu it provides a connect code.

When I type the code into the newest standalone amonguscapture .exe nothing happens at all. Not sure if this is expected behaviour? When I try it completely locally it works fine first time with no issues.

**Comment by denverquane** [comment]
Have to provide the hostname in `host.txt` co-located with the capture.exe, otherwise the capture has no idea what the ip/port of the discord bot would be :)
