### ISSUE TITLE
Trojan:Win32/Emali.A!cl

### ISSUE THREAD

**Issue by guryonblaze** [denverquane/amongusdiscord#60]
Windows defender is flagging AmongUsCapture.exe as containing Trojan:Win32/Emali.A!cl

**Comment by denverquane** [comment]
I built the .exes myself; definitely a false positive. But as the code is Open-Source, we highly encourage users to build the code from source themselves (and have instructions in the readme) if you have concerns :) In the future we may purchase a certificate to be able to sign the .exes ourselves

**Comment by guryonblaze** [comment]
just letting you know ;) thanks
