### ISSUE TITLE
[improvement] Dead (voice) chat?

### ISSUE THREAD

**Issue by Willdrick** [denverquane/amongusdiscord#63]
Would it be possible to have the bot move the dead players to a "dead chat" channel?
The idea would be that the dead person is moved after the discussion on the round of the player's death.
Then all dead players would be brought back into the "general" chat (but muted) during the discussion, and back to the "dead" channel (unmuted) for some fellow ghost banter.

Things that would be needed:
- Add a second channel bot assignment to "dead chat"
- Permission granted to move players back and forth
- Keep the currently dead player in "general" channel until after the discussion on the round of their death

**Comment by cakoshakib** [comment]
Hi, I think there is already a "dead voice chat" during the game as all the alive players are deafened and the dead people are unmuted so they can talk to each other.

**Comment by Willdrick** [comment]
oh, awesome, thanks!
