### ISSUE TITLE
Configurable default region/tracked voice channel

### ISSUE THREAD

**Issue by KMontag42** [denverquane/amongusdiscord#66]
from: https://github.com/denverquane/amongusdiscord/issues/55

good idea here to create a command to store default lobby region and tracked voice channel to the bot.

**Comment by jmengelle** [comment]
I agree !

**Comment by denverquane** [comment]
This is done, you can provide this via the `<guildid>_config.json` that is created on the bot's first startup

**Comment by jmengelle** [comment]
Could be useful to have some details ofthis json file in the readme.
