### ISSUE TITLE
Enhancement Request: Linked player count in bot message.

### ISSUE THREAD

**Issue by westonhowe98** [denverquane/amongusdiscord#68]
Add n/10 players to the game message in discord as a quick way to determine if everyone is linked.

**Comment by denverquane** [comment]
Good suggestion! Adding this, should be in 2.0.6 :)

**Comment by westonhowe98** [comment]
Thanks for the quick response, just submitted a pull request that adds this.

great project btw!

**Comment by denverquane** [comment]
Nice! You're fast! We came up with basically the same changes haha
