### ISSUE TITLE
Bot "forgets" to unmute some people

### ISSUE THREAD

**Issue by sirNugg3ts** [denverquane/amongusdiscord#7]
sometimes the bot will only partially unmute the people alive, even with a 450ms delay of discord commands

**Comment by webmail** [comment]
Could be an issue regarding your screen size. Are you on a standard 1080p monitor?

**Comment by KhaVNguyen** [comment]
Yep having trouble with unmuting working consistently. I'm on 1080p

**Comment by webmail** [comment]
Unfortunately, I cannot reproduce this. I run on 50ms and all is fine :-/
