### ISSUE TITLE
Among Us Capture cant connect when Discord Bot run in docker on different Host

### ISSUE THREAD

**Issue by justroot1337** [denverquane/amongusdiscord#70]
Hey,

first of all - u did and still do a really good job. Very nice project.

My Discord Bot run on a docker container on a server in my home network. when i try to link the capture with the code nothing happens. I think the discord bot just listing on localhost:8123 and the capture try to connect on locahost... Can u make it configurable? The discord bot have to listen on all local adress on the host and the capture need a adress to connect like 192.178.100.200:8123.
Then i could run the discord bot 24/7 in docker.

And a really could improvement would be a register-assistent.  I want to plan a new Session for 6 p.m. (e.x. .au new 6pm) and the other players can register before the session start. Then they are allready linked and everyone can see wether the lobby is full or not. When the lobby is created and catpure linked they can choose their color.
That would be awesome 👍 

Sorry for my bad english.
Keep up the good work!

**Comment by justroot1337** [comment]
sry, just realized in the code, that the host.txt solved my first problem :)

**Comment by Kalanur** [comment]
And what did you put into the host.txt? I've tried IP and IP:PORT but now the capture crashes every time I enter the code.
