### ISSUE TITLE
Have bot react with in-game colors during lobby

### ISSUE THREAD

**Issue by Sillocan** [denverquane/amongusdiscord#74]
Enhancement request: Have the bot react with color emojis which players should react with to pick a color.

Just how it reacts with `:x:` already

**Comment by denverquane** [comment]
Lol are you kidding? That's the entire purpose of the reactions; if all the colors don't pop up, give the bot a minute for Discord's caches to update to the bot correctly

**Comment by Sillocan** [comment]
I assumed it just didn't do it since it only added the :x: each time. 6th time running a game and it finally added the emotes. Seems to be hit or miss.
