### ISSUE TITLE
Final.txt file

### ISSUE THREAD

**Issue by hristijankiko** [denverquane/amongusdiscord#78]
Where is this final.txt file in the installation instructions? There is no link to the file anywhere it is mentioned in the Readme

**Comment by MK99MA** [comment]
You can find one in the  [2.0.4 pre-Release](https://github.com/denverquane/amongusdiscord/releases/tag/v2.0.4-prerelease), but overall its just a txt with this line:
`DISCORD_BOT_TOKEN = <YOUR TOKEN>`
that has to be in the same folder as your amongusdiscord.exe

**Comment by KMontag42** [comment]
answered. closing.

**Comment by Kyrluckechuck** [comment]
Can this be linked to in the documentation since I'm guessing most users wouldn't think to look in closed issues about where a referenced file is? Or even just to mention to search the past releases for the latest version of the `final.txt`!
