### ISSUE TITLE
Request: .au dead register the message writer as dead, and sending commands throught DM

### ISSUE THREAD

**Issue by sirNugg3ts** [denverquane/amongusdiscord#8]
.au dead @myname doesnt make a lot of sense when most of the time people will report themselves as dead when starting a meeting (not before or else people will see in chat someone has died).

Also to hide that someone is typing in chat that they're dead, it would be far better to just DM the bot and have it register the person as dead, else people can see someone typing in chat

**Comment by VoyagerPlaysGaming** [comment]
I think that would be a lot better

**Comment by denverquane** [comment]
Closing as sirNuggets and I have discussed this on our Discord server (and this will be added, or rather, addressed in a future release)
