### ISSUE TITLE
Remote discord bot

### ISSUE THREAD

**Issue by iReplayz** [denverquane/amongusdiscord#80]
i have make host.txt file not working
i have my bot on a VPS server and the capture at home i can't connect capture to the server anyone can help me ?

**Comment by denverquane** [comment]
Not without details of the problem, what versions you're on, what your host.txt looks like, etc.

Be descriptive

**Comment by iReplayz** [comment]
Version 2.2.0-Prerelease
Host file: http://90.103.125.228:8123

**Comment by MK99MA** [comment]
Is the port open? Idk about your VPS but I'm running the bot on a local Raspberry Pi and when I used my public IP in the host.txt I had to forward the used port first.

**Comment by iReplayz** [comment]
Yes port is open, but when i change the port on the host.txt on the cmd i have always
2020/09/28 18:36:53 2.2.0-Prerelease
2020/09/28 18:36:53 Invalid or no particular SERVER_PORT provided. Defaulting to 8123
2020/09/28 18:36:54 Bot is now running.  Press CTRL-C to exit.
2020/09/28 18:36:54 Serving at localhost:8123...

**Comment by denverquane** [comment]
The host.txt goes with the **capture**, not with the **discord**

**Comment by MK99MA** [comment]
the host.txt is in the same folder as your AmongUsCapture right? because the bot only requires the 'final.txt' (where you can also set the desired port like this:
`DISCORD_BOT_TOKEN= <token>
SERVER_PORT=8125`
