### ISSUE TITLE
discord nicknames

### ISSUE THREAD

**Issue by kjljxybr** [denverquane/amongusdiscord#81]
what about changing users discord nicknames to ingame nicknames after linking? guess it will be very helpful

**Comment by denverquane** [comment]
This is already a feature, but there's some restrictions in the discord api that make it a bit cumbersome: 
the discord server owner can never be nicknamed, 
and the bot's role has to be higher in your Roles list than other roles you want it to nickname, *even if the bot has Admin permissions*.

You can enable the feature by setting `applyNicknames` to `true` in your <guildid>_config.json (which is created the first time the bot starts up)
