### ISSUE TITLE
Config that allows dead players to communicate immediately after being killed

### ISSUE THREAD

**Issue by Dyljyn** [denverquane/amongusdiscord#83]
## Request

Provide a configuration that allows players who have just been killed to communicate, instead of having to wait until after the discussion round.

## Context

> We already have a method to stagger the dead player emojis until the discussion phase. We would wait to move players until the discussion phase
> 
> _Originally posted by @denverquane in https://github.com/denverquane/amongusdiscord/issues/32#issuecomment-696226575_

There is a valid reason for waiting until after the discussion round, which is that players cannot detect through discord that a player has been killed. However, my friends and I prioritize being able to speak when dead because some rounds can take time. So to satisfy both cases, I'm requesting a configuration.

**Comment by CRCError1970** [comment]
Similar to this request...

If it would be optionally possible to allow crewmate communication at all times, but move dead players to another channel.

We play the game as a group and our Discord "discipline" is pretty good already... But sometimes in the heat of the moment the game is spoiled.

**Comment by denverquane** [comment]
Added in the latest release :)

**Comment by fradali** [comment]
@denverquane how can i add this ? I think it's added in config.json but I don't know how to do it
