### ISSUE TITLE
Bot wont react

### ISSUE THREAD

**Issue by RobTech1** [denverquane/amongusdiscord#87]
When i make a new game with the bot with .au new it says HTTP 400 Bad Request, {"emoji_id": ["Value \":\" is not snowflake."]}
in the console

**Comment by denverquane** [comment]
This has been addressed on our discord multiple times; this is caused by the emojis not being fully added to the server right away (or rather, taking a long time to update the bot as to the existence of the emojis). Waiting a while and restarting the exe should resolve this.
