### ISSUE TITLE
amongusdiscord.exe 2.2.0 crashes after entering connect code in Among Us Capture

### ISSUE THREAD

**Issue by tech-ethos** [denverquane/amongusdiscord#89]
The bot is running (amongusdiscord.exe) and Among Us Capture is also running (amonguscapture-x64.exe). I use .au new in discord, then enter the provided connect code in Among Us Capture. amongusdiscord.exe immediately crashes after submitting the connect code. The log shows the following:

2020/09/30 11:51:44 Client connection closed:  client namespace disconnect
2020/09/30 11:51:44 meet error: runtime error: invalid memory address or nil pointer dereference

**Comment by TyraelElDruin** [comment]
Same issue - it seemed to work once, but every subsequent try seems to crash it.

**Comment by TyraelElDruin** [comment]
So the bot seems to be working now - I think it was related to not having all the emojis on the server.
