### ISSUE TITLE
Recomendation

### ISSUE THREAD

**Issue by VoyagerPlaysGaming** [denverquane/amongusdiscord#9]
you should make it so that if everyone names themselves after their discord the bot will automatically see they are dead in the game and see the username is the same as one in the discord vc and keep them muted automatically

**Comment by denverquane** [comment]
Thanks for the suggestion :) This is currently a feature already being actively developed; I'll close this issue when we release a version with this feature

**Comment by VoyagerPlaysGaming** [comment]
well that is awesome thanks for notifying me

**Comment by denverquane** [comment]
New pre-release should address this issue
