### ISSUE TITLE
Bot doesn't listen to config file. Creates new config file instead

### ISSUE THREAD

**Issue by aflacc** [denverquane/amongusdiscord#93]
it just created a new config file named `711270873214091274_config.json`
after running it again it made another named `760618610896273435_config.json`
They are both empty and contain no text.

edit: after stopping the bot, these files contain text.

**Comment by abdellahaski** [comment]
The part before "_config.json" is the discord server ID, each Discord server that the bot detects it's in it, the bot will add a config file of that server.
