### ISSUE TITLE
[Documentation] Add proper docs for all the possible options in the final.txt file

### ISSUE THREAD

**Issue by buthed010203** [denverquane/amongusdiscord#99]
~~Why not make them into one config.txt file, its a lot simpler and makes it easier if you ever want to add more global config stuff~~ shhh im dumb, would still probably make sense to add some more documentation

**Comment by denverquane** [comment]
We're in prerelease; I'm hesitant to spend a lot of time on documentation if things are constantly changing, but in general it might be a good idea to start doing it a bit more 👍

**Comment by buthed010203** [comment]
Yeah, I was just mentioning it for later, maybe add a section to the readme just dedicated to final.txt and all the config?

**Comment by denverquane** [comment]
Next update will have a few more env fields; added full documentation that should be in the next release :)

**Comment by buthed010203** [comment]
Addressed in [2.3.0](https://github.com/denverquane/amongusdiscord/releases/tag/v2.3.0)
